### ISSUE TITLE
Image processing code?

### ISSUE THREAD

**Issue by ddofer** [Emory-HITI/AI-Vengers#25]
Hi - Could you please release the code used for preprocessing the input images/Xrays? 
(Mainly to make comparisons against other datasets as equivalent as possible, and also to save on time?)

e.g. in the example CXR training scripts: 
 "`resnet34, **preprocess_input** = Classifiers.get('resnet34')`

(Xrays are greyscale, not RGB, and processing them to match the expected inputs of pretrained models can have gotchas in it. I'd rather use exactly what you did)

**Comment by anbhimi** [comment]
@ddofer,

In the example line -
`resnet34, preprocess_input = Classifiers.get('resnet34')`

The `preprocess_input` is an in-built function in Classifier Packages. The code does not require any additional preprocessing on the X-ray images.

**Comment by luisoala** [comment]
@ddofer as i  am going through these notebooks atm, see tfkeras Classifier objects here https://github.com/qubvel/classification_models/blob/master/classification_models/models/resnet.py

for resnets it seems it is the identity transform

`def preprocess_input(x, **kwargs):
    return x`

**Comment by anbhimi** [comment]
Closing the issue due to inactivity. Please re-open it if necessary.
Thank You
