### ISSUE TITLE
Open Source Data URL's are missing

### ISSUE THREAD

**Issue by anbhimi** [Emory-HITI/AI-Vengers#26]
URL's for the open-source datasets used in the experiments are missing in the `data` folder.

**Comment by anbhimi** [comment]
Open Source Data URLs are included at /data/README.md. Information regarding proprietary sources is not published.

**Comment by rachtibat** [comment]
Hi,

could you please also share the links for the race labels?
I can not find the labels for the CheXpert Dataset for example on https://aimi.stanford.edu/research/public-datasets .
I'd be glad, if you could point me to the right direction.

Thank you!

**Comment by blackboxradiology** [comment]
Sorry for the late reply!
CheXpert Demographic Data can be found at the link below.

https://stanfordaimi.azurewebsites.net/datasets/192ada7c-4d43-466e-b8bb-b81992bb80cf

Let it be known, some folks have had difficulty resolving this webpage.

**Comment by rachtibat** [comment]
No worries!

Works well, thanks a lot!
