### ISSUE TITLE
Explainable image classification

### ISSUE THREAD

**Issue by CanK93** [Emory-HITI/AI-Vengers#34]
Great work guys.

Maybe you can find something by using methods such as SHAP or LIME for Image classification.
Would be really interesting.

Here is a link: https://towardsdatascience.com/knowing-what-and-why-explaining-image-classifier-predictions-680a15043bad

Best
Can

**Comment by anbhimi** [comment]
Thank you for the suggestion.

Included the code for LIME Model Interpretation and Grad Cams at AI-Vengers/training_code/digital_hand_atlas/dha_2_image.ipynb.
