### ISSUE TITLE
Pathology detection training

### ISSUE THREAD

**Issue by dcalvo** [Emory-HITI/AI-Vengers#42]
Hi,

Super interesting research! I'm looking to replicate the results as part of my own group's research (for [ProjectX](https://www.uoft.ai/projectx-2021)). I've looked through the Densenet121 training notebooks, but noticed that they're exclusively for race detection (experiment A1). My group is interested in exploring the implicitly learned weights during pathology detection training (experiment A3). 

Am I correct in thinking that my group will have to train our own pathology detection algorithm as in experiment A3? Are there any pointers you could give us?

Thanks,
David

**Comment by blackboxradiology** [comment]
Hi David,

Thanks for reaching out! We are continuing to explore this bizarre phenomenon. You are correct, training a pathology detection model would be required to conduct experiment A3. I can submit a pull request with a notebook with the A3 experiment workflow if that would be helpful.

Best regards,
Brandon

**Comment by dcalvo** [comment]
Hi Brandon,

Absolutely, that would be very much appreciated! In return, I believe all of our work for the ProjectX competition is able to be open-sourced and we would be more than willing to share our findings. Thanks for the quick reply as well!

David

**Comment by blackboxradiology** [comment]
Hi David,

Please see the most recent version that includes the code for the transferred learning experiment.

**Comment by dcalvo** [comment]
This is great! Thank you, Brandon!
